# Form implementation generated from reading ui file 'interface/Admin_windows/personal_area.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_personal_area(object):
    def setupUi(self, personal_area):
        personal_area.setObjectName("personal_area")
        personal_area.resize(800, 550)
        personal_area.setMinimumSize(QtCore.QSize(800, 550))
        personal_area.setMaximumSize(QtCore.QSize(800, 550))
        self.centralwidget = QtWidgets.QWidget(parent=personal_area)
        self.centralwidget.setObjectName("centralwidget")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(290, 120, 221, 41))
        self.label_10.setStyleSheet("font-size: 28pt")
        self.label_10.setObjectName("label_10")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 450, 51, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(270, 380, 231, 41))
        self.label_1.setText("")
        self.label_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(0, -30, 800, 550))
        self.label_7.setMinimumSize(QtCore.QSize(600, 400))
        self.label_7.setMaximumSize(QtCore.QSize(800, 550))
        self.label_7.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(201, 218, 251, 255), stop:1 rgba(255, 255, 255, 255))")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(310, 320, 151, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(230, 185, 321, 121))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.label_8.setStyleSheet("font-size: 18pt")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.label_9.setStyleSheet("font-size: 18pt")
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        self.label_7.raise_()
        self.label_10.raise_()
        self.pushButton_4.raise_()
        self.label_1.raise_()
        self.pushButton_5.raise_()
        self.layoutWidget_2.raise_()
        personal_area.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=personal_area)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        personal_area.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=personal_area)
        self.statusbar.setObjectName("statusbar")
        personal_area.setStatusBar(self.statusbar)

        self.retranslateUi(personal_area)
        QtCore.QMetaObject.connectSlotsByName(personal_area)

    def retranslateUi(self, personal_area):
        _translate = QtCore.QCoreApplication.translate
        personal_area.setWindowTitle(_translate("personal_area", "MainWindow"))
        self.label_10.setText(_translate("personal_area", "Личный кабинет"))
        self.pushButton_4.setText(_translate("personal_area", "<-"))
        self.pushButton_5.setText(_translate("personal_area", "Изменить"))
        self.label_8.setText(_translate("personal_area", "Логин:"))
        self.label_9.setText(_translate("personal_area", "Пароль:"))
