# Form implementation generated from reading ui file 'interface/User_windows/book_ready.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_book_ready(object):
    def setupUi(self, book_ready):
        book_ready.setObjectName("book_ready")
        book_ready.resize(800, 550)
        book_ready.setMinimumSize(QtCore.QSize(800, 550))
        book_ready.setMaximumSize(QtCore.QSize(800, 550))
        self.centralwidget = QtWidgets.QWidget(parent=book_ready)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 100, 391, 41))
        self.label.setStyleSheet("font-size: 28pt")
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(260, 150, 301, 231))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 390, 141, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 450, 51, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, -30, 800, 550))
        self.label_6.setMinimumSize(QtCore.QSize(600, 400))
        self.label_6.setMaximumSize(QtCore.QSize(800, 550))
        self.label_6.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(201, 218, 251, 255), stop:1 rgba(255, 255, 255, 255))")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_6.raise_()
        self.label.raise_()
        self.tableWidget.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        book_ready.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=book_ready)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        book_ready.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=book_ready)
        self.statusbar.setObjectName("statusbar")
        book_ready.setStatusBar(self.statusbar)

        self.retranslateUi(book_ready)
        QtCore.QMetaObject.connectSlotsByName(book_ready)

    def retranslateUi(self, book_ready):
        _translate = QtCore.QCoreApplication.translate
        book_ready.setWindowTitle(_translate("book_ready", "MainWindow"))
        self.label.setText(_translate("book_ready", "Выберите подходящий номер"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("book_ready", "№"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("book_ready", "Тип"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("book_ready", "Цена"))
        self.pushButton.setText(_translate("book_ready", "Выбрать"))
        self.pushButton_2.setText(_translate("book_ready", "<-"))
