# Form implementation generated from reading ui file 'interface/User_windows/my_reserv.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_My_reserv(object):
    def setupUi(self, My_reserv):
        My_reserv.setObjectName("My_reserv")
        My_reserv.resize(800, 550)
        My_reserv.setMinimumSize(QtCore.QSize(800, 550))
        My_reserv.setMaximumSize(QtCore.QSize(800, 550))
        self.centralwidget = QtWidgets.QWidget(parent=My_reserv)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 80, 531, 71))
        self.label.setStyleSheet("font-size: 28pt")
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(100, 150, 601, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(560, 360, 141, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 450, 51, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, -20, 800, 550))
        self.label_6.setMinimumSize(QtCore.QSize(600, 400))
        self.label_6.setMaximumSize(QtCore.QSize(800, 550))
        self.label_6.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(201, 218, 251, 255), stop:1 rgba(255, 255, 255, 255))")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_6.raise_()
        self.label.raise_()
        self.tableWidget.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        My_reserv.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=My_reserv)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        My_reserv.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=My_reserv)
        self.statusbar.setObjectName("statusbar")
        My_reserv.setStatusBar(self.statusbar)

        self.retranslateUi(My_reserv)
        QtCore.QMetaObject.connectSlotsByName(My_reserv)

    def retranslateUi(self, My_reserv):
        _translate = QtCore.QCoreApplication.translate
        My_reserv.setWindowTitle(_translate("My_reserv", "MainWindow"))
        self.label.setText(_translate("My_reserv", "Номера, которые вы уже забронировали"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("My_reserv", "№"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("My_reserv", "Тип"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("My_reserv", "Число проживающих"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("My_reserv", "Цена"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("My_reserv", "Дата заселения"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("My_reserv", "Дата выселения"))
        self.pushButton.setText(_translate("My_reserv", "Удалить"))
        self.pushButton_2.setText(_translate("My_reserv", "<-"))
