# Form implementation generated from reading ui file 'interface/User_windows/user_menu.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_User_menu(object):
    def setupUi(self, User_menu):
        User_menu.setObjectName("User_menu")
        User_menu.resize(800, 550)
        User_menu.setMinimumSize(QtCore.QSize(800, 550))
        User_menu.setMaximumSize(QtCore.QSize(800, 550))
        self.centralwidget = QtWidgets.QWidget(parent=User_menu)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 130, 271, 51))
        self.label.setStyleSheet("font-size: 28pt")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 200, 200, 60))
        self.pushButton.setMinimumSize(QtCore.QSize(200, 60))
        self.pushButton.setMaximumSize(QtCore.QSize(200, 60))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 260, 200, 60))
        self.pushButton_2.setMinimumSize(QtCore.QSize(200, 60))
        self.pushButton_2.setMaximumSize(QtCore.QSize(200, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 320, 200, 60))
        self.pushButton_3.setMinimumSize(QtCore.QSize(200, 60))
        self.pushButton_3.setMaximumSize(QtCore.QSize(200, 60))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, -20, 800, 550))
        self.label_6.setMinimumSize(QtCore.QSize(600, 400))
        self.label_6.setMaximumSize(QtCore.QSize(800, 550))
        self.label_6.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(201, 218, 251, 255), stop:1 rgba(255, 255, 255, 255))")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_6.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        User_menu.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=User_menu)
        self.statusbar.setObjectName("statusbar")
        User_menu.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(parent=User_menu)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        User_menu.setMenuBar(self.menuBar)

        self.retranslateUi(User_menu)
        QtCore.QMetaObject.connectSlotsByName(User_menu)

    def retranslateUi(self, User_menu):
        _translate = QtCore.QCoreApplication.translate
        User_menu.setWindowTitle(_translate("User_menu", "MainWindow"))
        self.label.setText(_translate("User_menu", "Добро пожаловать !"))
        self.pushButton.setText(_translate("User_menu", "Забронировать номер"))
        self.pushButton_2.setText(_translate("User_menu", "Личный кабинет"))
        self.pushButton_3.setText(_translate("User_menu", "Моя бронь"))
