# Form implementation generated from reading ui file 'interface/Welcome_windows/enter.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_enter(object):
    def setupUi(self, enter):
        enter.setObjectName("enter")
        enter.resize(800, 550)
        enter.setMinimumSize(QtCore.QSize(800, 550))
        enter.setMaximumSize(QtCore.QSize(800, 550))
        self.centralwidget = QtWidgets.QWidget(parent=enter)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 390, 151, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 450, 51, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(230, 290, 291, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 70, 200, 200))
        self.label_3.setMinimumSize(QtCore.QSize(200, 200))
        self.label_3.setMaximumSize(QtCore.QSize(200, 200))
        self.label_3.setStyleSheet("background-image: url(logo.png); background-repeat:"
                                   " no-repeat; background-position: center")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 310, 231, 61))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, -20, 800, 550))
        self.label_6.setMinimumSize(QtCore.QSize(600, 400))
        self.label_6.setMaximumSize(QtCore.QSize(800, 550))
        self.label_6.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0,"
                                   " stop:0 rgba(201, 218, 251, 255), stop:1 rgba(255, 255, 255, 255))")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_6.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.layoutWidget.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        enter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=enter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        enter.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=enter)
        self.statusbar.setObjectName("statusbar")
        enter.setStatusBar(self.statusbar)

        self.retranslateUi(enter)
        QtCore.QMetaObject.connectSlotsByName(enter)

    def retranslateUi(self, enter):
        _translate = QtCore.QCoreApplication.translate
        enter.setWindowTitle(_translate("enter", "MainWindow"))
        self.pushButton.setText(_translate("enter", "Войти"))
        self.pushButton_2.setText(_translate("enter", "<-"))
        self.label_2.setText(_translate("enter", "Пароль:"))
        self.label.setText(_translate("enter", "Логин:"))
