# Form implementation generated from reading ui file 'interface/Welcome_windows/enter_or_reg.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Enter_or_reg(object):
    def setupUi(self, Enter_or_reg):
        Enter_or_reg.setObjectName("Enter_or_reg")
        Enter_or_reg.resize(800, 550)
        Enter_or_reg.setMinimumSize(QtCore.QSize(800, 550))
        Enter_or_reg.setMaximumSize(QtCore.QSize(800, 550))
        self.centralwidget = QtWidgets.QWidget(parent=Enter_or_reg)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(280, 320, 222, 102))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(220, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(220, 50))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(220, 50))
        self.pushButton_2.setMaximumSize(QtCore.QSize(220, 50))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 80, 200, 200))
        self.label.setMinimumSize(QtCore.QSize(200, 200))
        self.label.setMaximumSize(QtCore.QSize(200, 200))
        self.label.setStyleSheet("background-image: url(logo.png); background-repeat:"
                                 " no-repeat; background-position: center")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, -20, 800, 550))
        self.label_6.setMinimumSize(QtCore.QSize(600, 400))
        self.label_6.setMaximumSize(QtCore.QSize(800, 550))
        self.label_6.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, "
                                   "stop:0 rgba(201, 218, 251, 255), stop:1 rgba(255, 255, 255, 255))")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_6.raise_()
        self.layoutWidget.raise_()
        self.label.raise_()
        Enter_or_reg.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Enter_or_reg)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        Enter_or_reg.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Enter_or_reg)
        self.statusbar.setObjectName("statusbar")
        Enter_or_reg.setStatusBar(self.statusbar)

        self.retranslateUi(Enter_or_reg)
        QtCore.QMetaObject.connectSlotsByName(Enter_or_reg)

    def retranslateUi(self, Enter_or_reg):
        _translate = QtCore.QCoreApplication.translate
        Enter_or_reg.setWindowTitle(_translate("Enter_or_reg", "MainWindow"))
        self.pushButton.setText(_translate("Enter_or_reg", "Войти"))
        self.pushButton_2.setText(_translate("Enter_or_reg", "Зарегистрироваться"))
